### ISSUE TITLE
border-box

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/css-wipe#1]
``` css
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
```

http://www.paulirish.com/2012/box-sizing-border-box-ftw/
